#!/usr/bin/env bash
# First-run setup: creates .env with freshly generated secrets, then builds the
# database and seeds the demo account plus the template gallery.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "· .env already exists, leaving it alone"
else
  echo "· generating .env with fresh secrets"
  # node rather than openssl: node is already a hard requirement, openssl is not.
  rand() { node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"; }
  AUTH_SECRET=$(rand)
  ENCRYPTION_KEY=$(rand)
  cat > .env <<EOF
# Generated by scripts/setup.sh — do not commit this file.
DATABASE_URL="file:./dev.db"
AUTH_SECRET="${AUTH_SECRET}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"

# Optional. Without a key, AI nodes fall back to a deterministic simulated
# model so every flow still runs end to end.
OPENAI_API_KEY=""
OPENAI_BASE_URL="https://api.openai.com/v1"

NEXT_PUBLIC_APP_URL="http://localhost:3000"
EOF
fi

echo "· installing dependencies"
npm install --silent

echo "· creating the database schema"
npx prisma db push --skip-generate

echo "· seeding demo data"
npx tsx prisma/seed.ts

cat <<'EOF'

Ready. Start the dev server with:

  npm run dev

Then sign in at http://localhost:3000/login with:

  demo@wasl.app / wasl1234

EOF
